farahgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('posts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('shop/', include('shop.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import ProductDetail, Home, AddToCart, CartDetail, RemoveProductFromCart

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('cart/', CartDetail.as_view(), name='cart_detail'),
    path('category/<slug:slug>/', Home.as_view(), name='category_filter'),
    path('<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('cart/add/<int:product_id>', AddToCart.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', RemoveProductFromCart.as_view(), name='product_remove'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Profile


class Post(models.Model):
    date = models.DateTimeField()
    caption = models.TextField(max_length=200)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.caption[:50]

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.id})


class Comment(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    created = models.DateTimeField(null=True, auto_now_add=True)
    updated = models.DateTimeField(null=True, auto_now=True)

    class Meta:
        ordering = ('-created',)


class Like(models.Model):
    liker = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

accounts/views.py
from django.views.generic import CreateView, DetailView, UpdateView, ListView, View
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import SignUpForm, UpdateUserForm, UpdateProfileForm
from .models import Profile, Relationship

from posts.models import Post


class SignUpView(SuccessMessageMixin, CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
    success_message = " your account was created successfully"

    def form_valid(self, form):
        obj = form.save()
        profile = Profile(age=form.cleaned_data['age'],
                          user=obj)
        profile.save()
        return HttpResponseRedirect(reverse('login'))


class DashboardView(ListView):
    model = Post
    template_name = 'dashboard.html'

    def get_queryset(self):
        return Post.objects.filter(author__user_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = Profile.objects.get(user_id=self.kwargs['pk'])
        context['user_profile'] = user_profile
        is_following = False
        rel = Relationship.objects.filter(follows_id=user_profile.id, followed_by_id=self.request.user.profile.id)
        if rel.exists():
            is_following = True

        context['is_following'] = is_following
        return context


class ProfileView(DetailView):
    model = Profile
    template_name = 'profile_detail.html'

    def get_object(self, queryset=None):
        return Profile.objects.get(user_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = Profile.objects.get(user_id=self.kwargs['pk'])
        context['user_profile'] = user_profile
        is_following = False
        rel = Relationship.objects.filter(follows_id=user_profile.id, followed_by_id=self.request.user.profile.id)
        if rel.exists():
            is_following = True

        context['is_following'] = is_following
        return context


class UpdateProfileView(UpdateView):
    model = User
    form_class = UpdateUserForm
    second_form_class = UpdateProfileForm
    template_name = "profile_update.html"

    def get(self, request):
        self.object = self.get_object()
        form = self.form_class(instance=request.user)
        form2 = self.second_form_class(instance=request.user.profile)
        return self.render_to_response(self.get_context_data(
            object=self.object, form=form, form2=form2))

    def post(self, request):
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=request.user)
        form2 = self.second_form_class(request.POST, instance=request.user.profile)

        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(
                self.get_context_data(form=form, form2=form2, username=request.user.username))

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def get_success_url(self):
        return reverse('profile', kwargs={'pk': self.request.user.pk})


class MyLoginView(SuccessMessageMixin, LoginView):
    success_message = " you have logged in successfully"

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or reverse('profile', kwargs={'pk': self.request.user.pk})


class Follow(View):
    def post(self, request):
        profile = Profile.objects.get(id=request.user.profile.id)
        profile_to_follow = Profile.objects.get(id=request.POST['user_id'])
        if profile == profile_to_follow:
            raise Exception('you can not follow yourself!')

        rel = Relationship.objects.filter(followed_by_id=profile.id, follows_id=profile_to_follow.id)
        if rel.exists():
            return JsonResponse({'status': 'exist'})
        else:
            relation = Relationship(followed_by=profile, follows=profile_to_follow)
            relation.save()
            return JsonResponse({'status': 'ok'})


class UnFollow(View):
    def post(self, request):
        profile = Profile.objects.get(user_id=request.user.profile.user_id)
        profile_to_unfollow = Profile.objects.get(id=request.POST['user_id'])
        rel = Relationship.objects.filter(followed_by_id=profile.id, follows_id=profile_to_unfollow.id)
        if rel.exists():
            rel.delete()
            return JsonResponse({'status': 'ok'})
        else:
            return JsonResponse({'status': 'error'})

templates/base.html
{% load static %}
<head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <style>
        .aa a:link, a:visited {
    color: black;
    display: inline-block;
}


.aa a:hover, a:active {


    color: #6A8E9E;
}

#footeri {
    position: fixed;
    bottom: 0;
    width: 100%;
    height: 50px;
}

#login {
    padding-left: 20px;
}


.jumbotron {
    /*background-color: inherit;*/
    /*position: relative;*/
    height: 100%;
}

    </style>
</head>

<body id=body>
{% include 'inc/navbar.html' %}
<div class="jumbotron">
    <div class="container-fluid">
        {% include 'inc/messages.html' %}
        {% block content %}
        {% endblock content %}
    </div>
</div>


<div id="footeri">
    <footer class="page-footer text-center text-white bg-dark py-3 ">
        © 2020 Copyright:
        <a class="aa" href="{% url 'post' %}"> Farahgram</a>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
{% block js_files %}
{% endblock %}
</body>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>Posts</h2>
    <ul>
        {% for post in post_list %}
            <h4><a href="{{ post.get_absolute_url }}"> {{ post.caption }}</a></h4>
            <hr class="mt-2 mb-3"/>
        {% empty %}
            <p>no post</p>
        {% endfor %}

    </ul>
    <br>
    {% if   request.user.profile == user_profile %}
        <a href="{% url 'post_new' %}" class="btn btn-dark" role="button">+ New Post</a>

    {% elif  not is_following  and request.user.profile != user_profile %}
        <button id=following data-id="{{ user_profile.id }}" type="button" class="btn btn-dark">follow</button>

    {% elif is_following and request.user.profile != user_profile %}
        <button id=following data-id="{{ user_profile.id }}" type="button" class="btn btn-Warning">unfollow</button>
    {% endif %}

    {% block js_files %}
        <script src="{% static 'accounts/js/script.js' %}"></script>
    {% endblock %}


{% endblock content %}

templates/follow.html
{% extends 'base.html' %}
{% block content %}
    <h1>Add friend</h1>
    <p>you followed {{ profile.user_id }}</p>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% if post_list %}
        <h2>Posts</h2>
    {% endif %}

    <ul>
        {% if not post_list %}
            <br>
            <br>
            <h3>There is no post to show!
                Follow others to see their posts! </h3>
        {% endif %}
        {% for post in post_list %}
            <h2><a href="{{ post.get_absolute_url }}"> {{ post.caption }}</a></h2>
            <p><a href="{% url 'profile' post.author.user_id %}"> {{ post.author.user.username }}</a></p>
        {% endfor %}
    </ul>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete post</h1>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.date }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <h3> {{ post.date }}</h3>
        <p> {{ post.caption }} </p>
    </div>


    {% if user.is_authenticated and is_like %}
        <button id=like data-id="{{ post.id }}" type="button" class="btn btn-secondary">unlike</button>
    {% elif user.is_authenticated and not is_like %}
        <button id=like data-id="{{ post.id }}" type="button" class="btn btn-secondary">like</button>
    {% endif %}



    {% if user.is_authenticated %}
        <button id=comment data-id="{{ post.id }}" type="button" class="btn btn-secondary">comment</button>
        <br>
        <br>
        <form id="commentform" action="{% url 'comment_new' %}" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="Save">
            <input type="hidden" name="post_pk" value="{{ post.pk }}">
        </form>
    {% endif %}

    {% for comment in post.comment_set.all %}
        <div class="card bg-dark text-white p-3 m-5">
            {% if comment.is_reply == False %}
                <p>{{ comment.body }}</p>
                <p>commented by {{ comment.profile.user.username }} on {{ comment.created }}</p>
                <form action="{% url 'reply_new' post.pk comment.id %}" method="post">
                    {% csrf_token %}{{ reply_form.as_p }}
                    <input type="submit" value="Save">
                    <input type="hidden" name="post_pk" value="{{ post.pk }}">
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                </form>
            {% endif %}

            {% for reply in comment.comment_set.all %}
                <div class=" bg-primary text-white p-3 m-5 ">
                    <h1>{{ reply.body }}</h1>
                    <p>replied by {{ reply.profile.user.username }} on {{ reply.created }} on {{ comment.body }}</p>
                </div>
            {% endfor %}
        </div><br/>

    {% endfor %}

    {% if user.id == post.author.user_id %}
        <p></p><a href="{% url 'post_edit' post.pk %}"> +Edit Post</a></p>
        <p><a href="{% url 'post_delete' post.pk %}"> +Delete Post</a></p>
    {% endif %}

    {% block js_files %}
        <script src="{% static 'posts/js/script.js' %}"></script>
    {% endblock %}

{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}
{% block content %}
    <h1>Edit Post</h1>
    <form method="post">
        {% csrf_token %}{{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}
{% block content %}
    <h1>New Post</h1>
    <form method="post">
        {% csrf_token %}{{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

templates/profile_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div>
        <h5> first_name: {{ profile.user.first_name }}</h5>
        <h5> last_name: {{ profile.user.last_name }}</h5>
        <h5> age: {{ profile.age }}</h5>
        <h5> email: {{ profile.user.email }}</h5>
    </div>
    <br>
    <br>
    {% if profile.user_id == user.id %}
        <p><a href="{% url 'update_profile' %}"> + Edit Profile</a></p>
    {% endif %}

    <p><a href="{% url 'dashboard' profile.user_id %}"> + Dashboard</a></p>

    {% if  not is_following  and request.user.profile != user_profile %}
        <button id=following data-id="{{ user_profile.id }}" type="button" class="btn btn-Dark">follow</button>
    {% elif is_following %}
        <button id=following data-id="{{ user_profile.id }}" type="button" class="btn btn-Warning">unfollow</button>
    {% endif %}

    {% block js_files %}
        <script src="{% static 'accounts/js/script.js' %}"></script>
    {% endblock %}

{% endblock content %}

templates/profile_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Profile</h1>
    <form method="post">
        {% csrf_token %}{{ form.as_p }}{{ form2.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <h2>Sign up</h2>
    {% if user.is_authenticated %}
        <p> you are logged in!</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up</button>
            <a href="{% url 'social:begin' 'github' %}">signup with GitHub</a><br>
        </form>
    {% endif %}
{% endblock content %}

templates/unfollow.html
{% extends 'base.html' %}
{% block content %}
    <h1>unfollow</h1>
    <p>you have unfollowed {{ profile.user_id }}</p>
{% endblock content %}

templates/user_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}