farahgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('posts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('shop/', include('shop.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import ProductDetail, Home, AddToCart, CartDetail, RemoveProductFromCart

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('cart/', CartDetail.as_view(), name='cart_detail'),
    path('category/<slug:slug>/', Home.as_view(), name='category_filter'),
    path('<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('cart/add/<int:product_id>', AddToCart.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', RemoveProductFromCart.as_view(), name='product_remove'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory',
                                     null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_filter', args=[self.slug, ])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug, ])


class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount = models.IntegerField(blank=True, null=True, default=None)

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveSmallIntegerField(default=1)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.product.price * self.quantity

    class Meta:
        unique_together = ('product', 'order',)

shop/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)

shop/views.py
from django.shortcuts import get_object_or_404
from django.views import View
from django.shortcuts import redirect

from .models import Product, Category
from .cart import Cart
from django.views.generic import \
    ListView, DetailView, TemplateView
from .forms import CartAddForm


class Home(ListView):
    model = Product
    template_name = 'shop/home.html'

    def get_queryset(self):
        if "slug" in self.kwargs:
            category = get_object_or_404(Category, slug=self.kwargs['slug'])
            products = Product.objects.filter(category=category)
            return products
        else:
            return Product.objects.filter(available=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.filter(is_sub=False)
        context['categories'] = categories
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'shop/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = CartAddForm()
        return context


class AddToCart(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product=product, quantity=form.cleaned_data['quantity'])
        return redirect('shop:cart_detail')


class CartDetail(TemplateView):
    template_name = 'shop/cart_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        return context


class RemoveProductFromCart(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('shop:cart_detail')

shop/templates/shop/cart_detail.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'shop:product_remove' item.product.id %}">Remove </a></td>
    </tr>
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>

{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
    {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu">
                {% for sub in category.scategory.all %}
                    <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <br/><br/><br/>

    {% for product in product_list%}
        <div class="card" style="width: 11rem; height: 11rem; display:inline-block">
            {% thumbnail product.image "200x300" as img %}
                <img src="{{ img.url }}" class="card-img-top">
            {% endthumbnail %}
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ product.name }}</h3>
    <small>{{ product.created }}</small><p>{{ product.price }} Toman</p><br/>
    <form action="{% url 'shop:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ cart_form }}
        <input type="submit" value="Add to cart">
    </form>
    <img src="{{ product.image.url }}" alt="" width="400px" height="400px">
    <p>{{ product.description }}</p><br/><br/>
{% endblock %}