farahgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('posts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('shop/', include('shop.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import ProductDetail, Home, AddToCart, CartDetail, RemoveProductFromCart

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('cart/', CartDetail.as_view(), name='cart_detail'),
    path('category/<slug:slug>/', Home.as_view(), name='category_filter'),
    path('<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('cart/add/<int:product_id>', AddToCart.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', RemoveProductFromCart.as_view(), name='product_remove'),
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="aler alert-{{ message.tags }}  ">{{ message }}</p>
    {% endfor %}
{% endif  %}

templates/inc/navbar.html
<nav class="navbar fixed-top  bg-dark navbar-dark">
    <div class="container-fluid">
        <div class="navbar-header">

            <div class="navbar-brand">Farahgram</div>
            {% if user.is_authenticated %}
                <a class="text-secondary" href="{% url 'update_profile' %}">Profile</a>
                <a class="text-secondary" href="{% url 'dashboard' user.profile.user_id %}">Dashboard </a>
                <a class="text-secondary" href="{% url 'shop:home' %}">Shop </a>
                <a class="text-secondary" href="{% url 'shop:cart_detail' %}">Cart </a>
                <a class="text-secondary" href="{% url 'logout' %}">LogOut </a>


            {% elif  not user.is_authenticated %}
                <a class="text-secondary" href="{% url 'signup' %}">SignUp</a>
                <a class="text-secondary" href="{% url 'login' %}">LogIn</a>

            {% endif %}
        </div>
    </div>
</nav>